# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='fileRef',
            new_name='file',
        ),
    ]
