# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileObj', models.FileField(upload_to=b'./static/uploads/')),
                ('fileName', models.CharField(default=b'', max_length=20)),
                ('className', models.CharField(default=b'', max_length=20)),
            ],
        ),
    ]
