# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20160510_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completeProfile',
            field=models.BooleanField(default=False),
        ),
    ]
