# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_completeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
