# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20160518_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='login.User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta', to='login.User'),
        ),
    ]
