# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('studentID', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('TA', 'Teaching Assistant'), ('PR', 'Professor'), ('ST', 'Student')], default='ST', max_length=2)),
                ('profile_pic', models.CharField(default='N/A', max_length=200)),
                ('completeProfile', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='roster',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='home.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta', to='home.User'),
        ),
    ]
