# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
