# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('firstName', 'lastName', 'email')]),
        ),
    ]
