# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160429_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('TA', 'Teaching Assistant'), ('PR', 'Professor'), ('ST', 'Student')], default='ST', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='studentID',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('firstName', 'lastName')]),
        ),
    ]
