# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_course_roster'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([]),
        ),
    ]
